/*
 * To change this license header, choose License Headers in Project Properties. To change this template file, choose
 * Tools | Templates and open the template in the editor.
 */

/**
 *
 * @author andrzej.radziszewski
 */
public class TestFilemanager extends javax.swing.JFrame {

	/**
	 * Creates new form TestFilemanager
	 */
	public TestFilemanager() {

		this.initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		this.jPanel1 = new javax.swing.JPanel();
		this.jButton1 = new javax.swing.JButton();
		this.jButton2 = new javax.swing.JButton();
		this.jButton3 = new javax.swing.JButton();
		this.jButton4 = new javax.swing.JButton();
		this.jButton5 = new javax.swing.JButton();
		this.jButton6 = new javax.swing.JButton();
		this.jButton7 = new javax.swing.JButton();
		this.jButton8 = new javax.swing.JButton();
		this.jButton10 = new javax.swing.JButton();
		this.jButton9 = new javax.swing.JButton();
		this.jPanel2 = new javax.swing.JPanel();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		this.getContentPane()
			.setLayout(new java.awt.GridLayout(2, 2, 2, 0));

		this.jPanel1.setBackground(new java.awt.Color(204, 255, 204));
		this.jPanel1.setPreferredSize(new java.awt.Dimension(732, 50));
		this.jPanel1.setRequestFocusEnabled(false);
		this.jPanel1.setLayout(new java.awt.GridLayout(1, 10));

		this.jButton1.setText("jButton1");
		this.jPanel1.add(this.jButton1);

		this.jButton2.setText("jButton2");
		this.jPanel1.add(this.jButton2);

		this.jButton3.setText("jButton3");
		this.jPanel1.add(this.jButton3);

		this.jButton4.setText("jButton4");
		this.jPanel1.add(this.jButton4);

		this.jButton5.setText("jButton5");
		this.jPanel1.add(this.jButton5);

		this.jButton6.setText("jButton6");
		this.jPanel1.add(this.jButton6);

		this.jButton7.setText("jButton7");
		this.jPanel1.add(this.jButton7);

		this.jButton8.setText("jButton8");
		this.jPanel1.add(this.jButton8);

		this.jButton10.setText("jButton10");
		this.jPanel1.add(this.jButton10);

		this.jButton9.setText("jButton9");
		this.jPanel1.add(this.jButton9);

		this.getContentPane()
			.add(this.jPanel1);

		this.jPanel2.setBackground(new java.awt.Color(255, 255, 102));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(this.jPanel2);
		this.jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 790, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 236, Short.MAX_VALUE));

		this.getContentPane()
			.add(this.jPanel2);

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TestFilemanager.class.getName())
				.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TestFilemanager.class.getName())
				.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TestFilemanager.class.getName())
				.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TestFilemanager.class.getName())
				.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(() -> new TestFilemanager().setVisible(true));
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	// End of variables declaration//GEN-END:variables
}
