/*
 * To change this license header, choose License Headers in Project Properties. To change this template file, choose
 * Tools | Templates and open the template in the editor.
 */
package com.codigo.aplios.toolbox.xbase.gui.forms;

import java.awt.Component;
import java.awt.Rectangle;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andrzej.radziszewski
 */
public class frmDasboard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public frmDasboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlOption = new javax.swing.JPanel();
        barOption = new javax.swing.JToolBar();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mnuMain = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XBase Workspace ver. 2017.1");
        setMinimumSize(new java.awt.Dimension(800, 600));

        pnlMain.setBackground(new java.awt.Color(153, 204, 255));
        pnlMain.setName("pnlMain"); // NOI18N
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlLeft.setBackground(new java.awt.Color(102, 255, 204));
        pnlLeft.setPreferredSize(new java.awt.Dimension(200, 711));

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );

        pnlMain.add(pnlLeft, java.awt.BorderLayout.WEST);

        pnlOption.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlOption.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pnlOption.setFocusable(false);
        pnlOption.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlOption.setPreferredSize(new java.awt.Dimension(770, 67));
        pnlOption.setRequestFocusEnabled(false);
        pnlOption.setVerifyInputWhenFocusTarget(false);
        pnlOption.setLayout(new java.awt.BorderLayout());

        barOption.setBorder(null);
        barOption.setFloatable(false);
        barOption.setAutoscrolls(true);
        barOption.setDoubleBuffered(true);
        barOption.setFocusCycleRoot(true);
        barOption.setMaximumSize(new java.awt.Dimension(237, 62));
        barOption.setMinimumSize(new java.awt.Dimension(237, 62));
        barOption.setPreferredSize(new java.awt.Dimension(107, 62));
        barOption.setRequestFocusEnabled(false);
        barOption.setVerifyInputWhenFocusTarget(false);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-menu.png"))); // NOI18N
        jButton5.setText("Operacje");
        jButton5.setAlignmentX(0.5F);
        jButton5.setAutoscrolls(true);
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setRequestFocusEnabled(false);
        jButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-merge-cells.png"))); // NOI18N
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barOption.add(jButton5);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-insert-row-above(1).png"))); // NOI18N
        jButton6.setText("Nowy rekord");
        jButton6.setAlignmentX(0.5F);
        jButton6.setAutoscrolls(true);
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setRequestFocusEnabled(false);
        jButton6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-merge-cells.png"))); // NOI18N
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barOption.add(jButton6);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-grid.png"))); // NOI18N
        jButton7.setText("Struktura");
        jButton7.setAlignmentX(0.5F);
        jButton7.setAutoscrolls(true);
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setRequestFocusEnabled(false);
        jButton7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-merge-cells.png"))); // NOI18N
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barOption.add(jButton7);

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-monitor.png"))); // NOI18N
        jButton8.setText("Monitoring");
        jButton8.setAlignmentX(0.5F);
        jButton8.setAutoscrolls(true);
        jButton8.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setRequestFocusEnabled(false);
        jButton8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-merge-cells.png"))); // NOI18N
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barOption.add(jButton8);

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-support.png"))); // NOI18N
        jButton9.setText("Preferencje");
        jButton9.setAlignmentX(0.5F);
        jButton9.setAutoscrolls(true);
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setRequestFocusEnabled(false);
        jButton9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-merge-cells.png"))); // NOI18N
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barOption.add(jButton9);

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-synchronize.png"))); // NOI18N
        jButton10.setText("Synchronizacja");
        jButton10.setAlignmentX(0.5F);
        jButton10.setAutoscrolls(true);
        jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-merge-cells.png"))); // NOI18N
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barOption.add(jButton10);

        pnlOption.add(barOption, java.awt.BorderLayout.CENTER);

        pnlMain.add(pnlOption, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 682));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );

        pnlMain.add(jPanel1, java.awt.BorderLayout.EAST);

        jScrollPane1.setBorder(null);

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setDoubleBuffered(true);
        jTable1.setDragEnabled(true);
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        pnlMain.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        mnuMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));

        jMenu8.setText("Application");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Settings");
        jMenu8.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenu8.add(jMenuItem3);
        jMenu8.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        mnuMain.add(jMenu8);

        jMenu1.setText("Database");
        mnuMain.add(jMenu1);

        jMenu4.setText("Table");
        mnuMain.add(jMenu4);

        jMenu11.setText("Index");
        mnuMain.add(jMenu11);

        jMenu2.setText("Record");
        mnuMain.add(jMenu2);

        jMenu7.setText("Search");
        mnuMain.add(jMenu7);

        jMenu9.setText("Tasks");
        mnuMain.add(jMenu9);

        jMenu10.setText("Scheduler");
        mnuMain.add(jMenu10);

        jMenu5.setText("Tools");
        mnuMain.add(jMenu5);

        jMenu6.setText("Window");
        mnuMain.add(jMenu6);

        jMenu3.setLabel("Help");
        mnuMain.add(jMenu3);

        setJMenuBar(mnuMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFillsViewportHeight(true);
        jTable1.setComponentPopupMenu(new TablePopupMenu());
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args
     *             the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels())
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDasboard.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        // </editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(() -> {
            final JFrame form = new frmDasboard();
            form.setLocationRelativeTo(null);
            form.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barOption;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar mnuMain;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlOption;
    // End of variables declaration//GEN-END:variables

}

class TablePopupMenu extends JPopupMenu {

    private final JMenuItem delete;

    protected TablePopupMenu() {
        super();
        add("add").addActionListener(e -> {
            JTable table = (JTable)getInvoker();
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            model.addRow(new Object[]{"1", "2", "3", "4"});
            model.
                    addRow(new Object[]{"3 dasd1", "ąśął", "q wq  w   qw  qw", "123123"});
            model.addRow(new Object[]{"1", "2", "3", "4"});
            model.
                    addRow(new Object[]{"3 dasd1", "ąśął", "q wq  w   qw  qw", "123123"});
            model.addRow(new Object[]{"1", "2", "3", "4"});
            model.
                    addRow(new Object[]{"3 dasd1", "ąśął", "q wq  w   qw  qw", "123123"});
            model.addRow(new Object[]{"1", "2", "3", "4"});
            model.addRow(new Object[]{"1", "2", "3", "4"});
            model.
                    addRow(new Object[]{"3 dasd1", "ąśął", "q wq  w   qw  qw", "123123"});
            model.
                    addRow(new Object[]{"3 dasd1", "ąśął", "q wq  w   qw  qw", "123123"});
            Rectangle r = table.getCellRect(model.getRowCount() - 1, 0, true);
            table.scrollRectToVisible(r);
        });
        addSeparator();
        delete = add("delete");
        delete.addActionListener(e -> {
            JTable table = (JTable)getInvoker();
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            int[] selection = table.getSelectedRows();
            for (int i = selection.length - 1; i >= 0; i--)
                model.removeRow(table.convertRowIndexToModel(selection[i]));
        });
    }

    @Override
    public void show(Component c, int x, int y) {
        if (c instanceof JTable) {
            delete.setEnabled(((JTable)c).getSelectedRowCount() > 0);
            super.show(c, x, y);
        }
    }

}
